from __future__ import annotations

from typing import Any


ACTION_LIBRARY_VERSION = 1

ACTION_CATEGORIES = [
    "Widgets",
    "Layers",
    "Workspace",
    "Annotation",
    "Enhance",
    "Visualize",
    "Measure",
    "Masks",
    "Montage",
    "Segmentation",
    "Spectral",
]


ACTION_RECORDS: list[dict[str, Any]] = [
    {
        "id": "widget_open_intensity_metrics",
        "title": "ROI Intensity Analysis",
        "category": "Widgets",
        "description": "Open the ROI intensity analysis workspace for the current viewer.",
        "tags": ["widget", "measure", "roi", "intensity"],
        "best_for": "Interactive ROI-based signal measurement from Shapes annotations without writing code or asking chat.",
        "expected_input": "One or more image layers, and optionally a selected or paired Shapes ROI layer.",
        "load_prompt": "Open ROI intensity analysis.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "function",
            "target": "open_intensity_metrics_widget",
        },
    },
    {
        "id": "widget_open_group_comparison",
        "title": "Group Comparison Statistics",
        "category": "Widgets",
        "description": "Open the interactive group comparison statistics workspace for image-level or ROI-derived measurements.",
        "tags": ["widget", "compare", "stats", "group"],
        "best_for": "Comparing two experimental groups with descriptive statistics, assumption checks, plots, and statistical test summaries.",
        "expected_input": "Image layers or grouped ROI/image naming patterns already present in the viewer.",
        "load_prompt": "Open group comparison statistics.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "open_group_comparison_widget",
            "arguments": {},
        },
    },
    {
        "id": "widget_open_line_profile_fit",
        "title": "Line Profile Analysis",
        "category": "Widgets",
        "description": "Open the line-profile analysis workspace for the current viewer.",
        "tags": ["widget", "line-profile", "gaussian", "measure"],
        "best_for": "Interactive line-scan measurement with Gaussian fitting for profile width and peak analysis.",
        "expected_input": "An image layer and a line-like Shapes ROI when you want to sample a profile.",
        "load_prompt": "Open line profile analysis.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "function",
            "target": "open_line_profile_gaussian_fit_widget",
        },
    },
    {
        "id": "layers_list_layers",
        "title": "Layer List",
        "category": "Layers",
        "description": "Summarize the currently open layers in the viewer.",
        "tags": ["layers", "inspect", "list"],
        "best_for": "Quickly checking what images, labels, shapes, and points layers are open.",
        "expected_input": "Open layers in the current viewer.",
        "load_prompt": "List the current layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "list_layers",
            "arguments": {},
        },
    },
    {
        "id": "layers_inspect_selected",
        "title": "Layer Properties",
        "category": "Layers",
        "description": "Inspect the active selected layer and summarize its properties.",
        "tags": ["layers", "inspect", "selected-layer"],
        "best_for": "Checking shape, dtype, semantic type, and quick details of the active layer.",
        "expected_input": "A selected layer in the viewer.",
        "load_prompt": "Inspect the selected layer.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "inspect_selected_layer",
            "arguments": {},
        },
    },
    {
        "id": "layers_delete_all",
        "title": "Delete All",
        "category": "Layers",
        "description": "Delete every layer in the current viewer.",
        "tags": ["layers", "delete", "clear-viewer"],
        "best_for": "Resetting the viewer quickly before loading a fresh set of layers.",
        "expected_input": "Any open layers in the current viewer.",
        "load_prompt": "Delete all layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "delete_all_layers",
            "arguments": {},
        },
    },
    {
        "id": "layers_delete_shape_layers",
        "title": "Delete ROI Layers",
        "category": "Layers",
        "description": "Delete all Shapes ROI layers from the current viewer.",
        "tags": ["layers", "delete", "shapes", "roi"],
        "best_for": "Cleaning up temporary ROI or tile-box shapes layers quickly.",
        "expected_input": "Any open Shapes layers you want to remove.",
        "load_prompt": "Delete all ROI shape layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "delete_layers",
            "arguments": {"layer_type": "shapes"},
        },
    },
    {
        "id": "layers_delete_point_layers",
        "title": "Delete Point Annotations",
        "category": "Layers",
        "description": "Delete all Points layers from the current viewer.",
        "tags": ["layers", "delete", "points"],
        "best_for": "Cleaning up temporary annotation or SAM prompt point layers quickly.",
        "expected_input": "Any open Points layers you want to remove.",
        "load_prompt": "Delete all point layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "delete_layers",
            "arguments": {"layer_type": "points"},
        },
    },
    {
        "id": "layers_show_all",
        "title": "Show All",
        "category": "Layers",
        "description": "Turn all layers back on in the current viewer.",
        "tags": ["layers", "visibility", "show"],
        "best_for": "Recovering from layer isolation or hidden-layer workflows.",
        "expected_input": "Open layers in the current viewer.",
        "load_prompt": "Show all layers again.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "show_all_layers",
            "arguments": {},
        },
    },
    {
        "id": "layers_hide_all",
        "title": "Hide All",
        "category": "Layers",
        "description": "Turn every layer off in the current viewer.",
        "tags": ["layers", "visibility", "hide"],
        "best_for": "Clearing the canvas quickly before isolating one layer or rebuilding visibility.",
        "expected_input": "Open layers in the current viewer.",
        "load_prompt": "Hide all layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "hide_all_layers",
            "arguments": {},
        },
    },
    {
        "id": "layers_hide_all_but_selected",
        "title": "Isolate Selected",
        "category": "Layers",
        "description": "Keep only the selected layer visible and hide all other layers.",
        "tags": ["layers", "visibility", "selected-layer", "isolate"],
        "best_for": "Quickly isolating the active image or annotation layer when many layers are open.",
        "expected_input": "A selected layer in the current viewer. If nothing is selected, the tool will ask for a target layer.",
        "load_prompt": "Hide all layers except the selected layer.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "show_only_layers",
            "arguments": {},
        },
    },
    {
        "id": "layers_set_pixel_size_0_1",
        "title": "Set Uniform Scale 0.1",
        "category": "Layers",
        "description": "Set the selected layer scale to 0.1 on every axis. For 3D data, napari scale order is (z, y, x).",
        "tags": ["layers", "scale", "pixel-size", "selected-layer"],
        "best_for": "Quickly assigning one uniform scale value to the active layer when you want a deterministic shortcut.",
        "expected_input": "A selected layer with a scale property, such as Image, Labels, Shapes, or Points. In 3D, scale order is (z, y, x).",
        "load_prompt": "Set the selected layer scale to 0.1 on every axis.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "set_layer_scale",
            "arguments": {"scale": 0.1},
        },
    },
    {
        "id": "layers_reset_pixel_size",
        "title": "Reset Uniform Scale",
        "category": "Layers",
        "description": "Reset the selected layer scale to 1 on every axis. For 3D data, napari scale order is (z, y, x).",
        "tags": ["layers", "scale", "pixel-size", "selected-layer", "reset"],
        "best_for": "Returning the active layer to a uniform scale of 1 across all dimensions.",
        "expected_input": "A selected layer with a scale property, such as Image, Labels, Shapes, or Points. In 3D, scale order is (z, y, x).",
        "load_prompt": "Reset the selected layer scale to 1 on every axis.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "set_layer_scale",
            "arguments": {"scale": 1.0},
        },
    },
    {
        "id": "workspace_save",
        "title": "Save Workspace",
        "category": "Workspace",
        "description": "Save the current viewer workspace to the last workspace file path.",
        "tags": ["workspace", "save", "session"],
        "best_for": "Quickly saving the current viewer state without choosing a new file each time.",
        "expected_input": "Current viewer layers and display state.",
        "load_prompt": "Save the current workspace.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "function",
            "target": "save_workspace",
        },
    },
    {
        "id": "workspace_save_as",
        "title": "Save Workspace As",
        "category": "Workspace",
        "description": "Save the current viewer workspace to a new manifest file.",
        "tags": ["workspace", "save-as", "session"],
        "best_for": "Creating a new saved workspace file or naming a new workspace version.",
        "expected_input": "Current viewer layers and display state.",
        "load_prompt": "Save the current workspace as a new file.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "function",
            "target": "save_workspace_as",
        },
    },
    {
        "id": "workspace_load",
        "title": "Load Workspace",
        "category": "Workspace",
        "description": "Choose and load a saved workspace manifest.",
        "tags": ["workspace", "load", "session"],
        "best_for": "Opening a specific saved workspace file from disk.",
        "expected_input": "A previously saved workspace manifest file.",
        "load_prompt": "Load a saved workspace.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "function",
            "target": "load_workspace",
        },
    },
    {
        "id": "workspace_restore_last",
        "title": "Restore Last Workspace",
        "category": "Workspace",
        "description": "Reload the last workspace file used by the plugin.",
        "tags": ["workspace", "restore", "session"],
        "best_for": "Getting back to the most recently saved or loaded workspace quickly.",
        "expected_input": "A previously used workspace path remembered by the plugin.",
        "load_prompt": "Restore the last workspace.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "function",
            "target": "restore_last_workspace",
        },
    },
    {
        "id": "annotation_add_text_label",
        "title": "Add Text Annotation",
        "category": "Annotation",
        "description": "Add a non-destructive text label overlay to the selected image or anchor layer.",
        "tags": ["annotation", "text", "points", "overlay"],
        "best_for": "Placing a visible note in viewer space without changing image pixels.",
        "expected_input": "A selected 2D or 3D layer and a position supplied through chat or action editing.",
        "load_prompt": "Write a text annotation on the selected layer.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "create_text_annotation",
            "arguments": {"text": "note", "position": [0, 0]},
        },
    },
    {
        "id": "annotation_list_text_labels",
        "title": "List Text Annotations",
        "category": "Annotation",
        "description": "List the current text labels stored in the managed text annotation layer.",
        "tags": ["annotation", "text", "inspect", "list"],
        "best_for": "Checking what text overlays already exist before renaming, deleting, or adding more.",
        "expected_input": "A managed text annotation points layer, selected or otherwise available in the viewer.",
        "load_prompt": "List the text annotations on the current annotation layer.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "list_text_annotations",
            "arguments": {},
        },
    },
    {
        "id": "annotation_numbered_callouts",
        "title": "Numbered Callouts",
        "category": "Annotation",
        "description": "Build numbered outside callout boxes with leader lines for each object in a labels layer.",
        "tags": ["annotation", "callout", "numbered", "labels"],
        "best_for": "Turning segmented objects into figure-style numbered labels that sit beside the object instead of on top of it.",
        "expected_input": "A selected or named 2D Labels layer with one or more labeled objects.",
        "load_prompt": "Annotate the current labels layer with numbered outside callouts.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "annotate_labels_with_callouts",
            "arguments": {"prefix": "particle", "start_index": 1, "replace_existing": True},
        },
    },
    {
        "id": "annotation_title_label",
        "title": "Title Label",
        "category": "Annotation",
        "description": "Add a boxed title label near the top of the selected 2D layer.",
        "tags": ["annotation", "title", "box", "overlay"],
        "best_for": "Adding a non-destructive heading like WT Group N=10 or Control to an image panel.",
        "expected_input": "A selected 2D layer and a title string.",
        "load_prompt": "Add a boxed title label above the selected layer.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "create_title_label",
            "arguments": {"text": "WT Group N=10", "placement": "outside_top", "align": "left"},
        },
    },
    {
        "id": "annotation_rename_text_label",
        "title": "Rename Text Annotation",
        "category": "Annotation",
        "description": "Rename one text label in the managed text annotation layer.",
        "tags": ["annotation", "text", "rename", "edit"],
        "best_for": "Correcting or updating an existing overlay label without moving it.",
        "expected_input": "An existing text annotation plus the replacement text.",
        "load_prompt": "Rename a text annotation.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "rename_text_annotation",
            "arguments": {"old_text": "old label", "new_text": "new label"},
        },
    },
    {
        "id": "annotation_delete_text_label",
        "title": "Delete Text Annotation",
        "category": "Annotation",
        "description": "Delete one text label or clear the managed text annotation layer.",
        "tags": ["annotation", "text", "delete", "clear"],
        "best_for": "Removing incorrect or temporary text overlays without touching the source image.",
        "expected_input": "A managed text annotation layer and optionally the exact text to remove.",
        "load_prompt": "Delete a text annotation.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "delete_text_annotation",
            "arguments": {"text": "label to remove"},
        },
    },
    {
        "id": "enhance_gaussian_denoise",
        "title": "Gaussian Blur",
        "category": "Enhance",
        "description": "Apply Gaussian blur to the selected image layer.",
        "tags": ["enhance", "gaussian", "denoise", "selected-layer"],
        "best_for": "Quick smoothing of a grayscale image before thresholding or inspection.",
        "expected_input": "A selected grayscale image layer.",
        "load_prompt": "Apply Gaussian blur to the selected image with sigma 1.0.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "gaussian_denoise",
            "arguments": {"sigma": 1.0},
        },
    },
    {
        "id": "enhance_apply_clahe",
        "title": "Enhance Contrast (CLAHE)",
        "category": "Enhance",
        "description": "Apply CLAHE local contrast enhancement to the selected image.",
        "tags": ["enhance", "clahe", "contrast", "selected-layer"],
        "best_for": "Improving local contrast in grayscale images before visual inspection or thresholding.",
        "expected_input": "A selected grayscale image layer.",
        "load_prompt": "Apply CLAHE to the selected image.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "apply_clahe",
            "arguments": {},
        },
    },
    {
        "id": "enhance_apply_clahe_batch",
        "title": "Enhance Contrast Batch",
        "category": "Enhance",
        "description": "Apply CLAHE to all compatible image layers in the viewer.",
        "tags": ["enhance", "clahe", "batch", "contrast"],
        "best_for": "Applying the same contrast enhancement to several open grayscale image layers at once.",
        "expected_input": "Two or more grayscale image layers.",
        "load_prompt": "Apply CLAHE to all open image layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "apply_clahe_batch",
            "arguments": {},
        },
    },
    {
        "id": "visualize_quick_compare_grid",
        "title": "Tile Images",
        "category": "Visualize",
        "description": "Tile the open image layers for side-by-side comparison.",
        "tags": ["visualize", "grid", "compare", "viewer"],
        "best_for": "Fast side-by-side image comparison without moving layer data.",
        "expected_input": "Two or more open image layers.",
        "load_prompt": "Tile the open image layers for comparison.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "show_image_layers_in_grid",
            "arguments": {"spacing": 2},
        },
    },
    {
        "id": "visualize_turn_off_grid",
        "title": "Untile Images",
        "category": "Visualize",
        "description": "Turn off tiled image view and return to the normal overlapping display.",
        "tags": ["visualize", "grid", "viewer", "restore"],
        "best_for": "Returning from grid comparison mode to standard viewing.",
        "expected_input": "A viewer currently in image grid mode.",
        "load_prompt": "Untile the images and return to the normal view.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "hide_image_grid_view",
            "arguments": {},
        },
    },
    {
        "id": "visualize_presentation_layout",
        "title": "Make Presentation Montage",
        "category": "Visualize",
        "description": "Arrange open layers as presentation copies in one viewer space.",
        "tags": ["visualize", "presentation", "layout", "copies"],
        "best_for": "Curated side-by-side layouts for display or figure preparation.",
        "expected_input": "Two or more compatible image or labels layers.",
        "load_prompt": "Make a presentation montage from the open image layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "arrange_layers_for_presentation",
            "arguments": {"layout": "row", "spacing": 20, "use_copies": True, "match_origin": True},
        },
    },
    {
        "id": "visualize_max_projection",
        "title": "Max Intensity Projection",
        "category": "Visualize",
        "description": "Create a max-intensity projection from the selected 3D grayscale image.",
        "tags": ["visualize", "projection", "mip", "selected-layer"],
        "best_for": "Flattening a 3D grayscale image into a quick 2D overview.",
        "expected_input": "A selected 3D grayscale image layer.",
        "load_prompt": "Create a max intensity projection from the selected image along axis 0.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "project_max_intensity",
            "arguments": {"axis": 0},
        },
    },
    {
        "id": "measure_summary_stats",
        "title": "Measure Intensity",
        "category": "Measure",
        "description": "Summarize intensity statistics for the selected image layer.",
        "tags": ["measure", "intensity", "stats", "selected-layer"],
        "best_for": "Checking mean, std, median, min, and max for one image quickly.",
        "expected_input": "A selected image layer.",
        "load_prompt": "Summarize intensity statistics for the selected image.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "summarize_intensity",
            "arguments": {},
        },
    },
    {
        "id": "measure_histogram",
        "title": "Plot Histogram",
        "category": "Measure",
        "description": "Plot a histogram for the selected image layer.",
        "tags": ["measure", "histogram", "intensity", "selected-layer"],
        "best_for": "Inspecting the intensity distribution of one image layer quickly.",
        "expected_input": "A selected image layer.",
        "load_prompt": "Plot a histogram for the selected image with 64 bins.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "plot_histogram",
            "arguments": {"bins": 64},
        },
    },
    {
        "id": "measure_inspect_roi_context",
        "title": "ROI Summary",
        "category": "Measure",
        "description": "Summarize the selected or active ROI layer and its spatial extent.",
        "tags": ["measure", "roi", "inspect", "selected-layer"],
        "best_for": "Checking which shapes or labels ROI is currently active before measurement.",
        "expected_input": "A selected or active Shapes or Labels ROI layer.",
        "load_prompt": "Inspect the current ROI context.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "inspect_roi_context",
            "arguments": {},
        },
    },
    {
        "id": "measure_shapes_roi_stats",
        "title": "Measure ROI",
        "category": "Measure",
        "description": "Summarize centroid, bbox, area, and intensity stats for the current Shapes ROI.",
        "tags": ["measure", "roi", "shapes", "stats"],
        "best_for": "Quick textual ROI summaries before using the fuller ROI Intensity Analysis widget.",
        "expected_input": "A Shapes ROI layer, and optionally an image layer if you want intensity values.",
        "load_prompt": "Measure the current Shapes ROI stats.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "measure_shapes_roi_stats",
            "arguments": {},
        },
    },
    {
        "id": "measure_extract_roi_values",
        "title": "ROI Intensity Summary",
        "category": "Measure",
        "description": "Extract intensity values from the selected ROI and summarize them.",
        "tags": ["measure", "roi", "intensity"],
        "best_for": "Quick ROI value summaries without opening a dedicated widget.",
        "expected_input": "An image layer and a Shapes or Labels ROI layer.",
        "load_prompt": "Extract ROI values from the current image using the current ROI.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "extract_roi_values",
            "arguments": {},
        },
    },
    {
        "id": "measure_measure_mask_batch",
        "title": "Measure Masks",
        "category": "Measure",
        "description": "Measure all labels or mask layers in the current viewer.",
        "tags": ["measure", "mask", "batch", "labels"],
        "best_for": "Quickly comparing area and object counts across several mask layers.",
        "expected_input": "One or more labels layers.",
        "load_prompt": "Measure all mask layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "measure_mask_batch",
            "arguments": {},
        },
    },
    {
        "id": "measure_labels_table",
        "title": "Analyze Particles Table",
        "category": "Measure",
        "description": "Measure the selected labels layer as a region-properties table.",
        "tags": ["measure", "labels", "table", "selected-layer"],
        "best_for": "Per-object measurements such as centroid, bbox, area, and intensity summaries.",
        "expected_input": "A selected Labels layer, and optionally an intensity image layer if the tool asks for one.",
        "load_prompt": "Analyze particles in the selected labels layer as a table.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "measure_labels_table",
            "arguments": {},
        },
    },
    {
        "id": "measure_mask",
        "title": "Measure Mask",
        "category": "Measure",
        "description": "Measure the selected mask or labels layer.",
        "tags": ["measure", "mask", "labels", "selected-layer"],
        "best_for": "Quick area or object-count measurement on the active mask.",
        "expected_input": "A selected Labels layer or binary mask-like labels layer.",
        "load_prompt": "Measure the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "measure_mask",
            "arguments": {},
        },
    },
    {
        "id": "masks_preview_threshold",
        "title": "Threshold Preview",
        "category": "Masks",
        "description": "Preview a threshold-derived mask from the selected image layer.",
        "tags": ["mask", "threshold", "preview", "selected-layer"],
        "best_for": "Trying threshold-based segmentation before committing to a labels layer.",
        "expected_input": "A selected grayscale image layer.",
        "parameter_hints": [
            "Default polarity is auto.",
            "Adjust polarity with bright or dim when the foreground is known.",
        ],
        "prompt_examples": [
            "Preview thresholding on the selected image with polarity bright.",
            "Preview thresholding on image_a with polarity dim.",
        ],
        "load_prompt": "Preview thresholding on the selected image.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "preview_threshold",
            "arguments": {"polarity": "auto"},
        },
    },
    {
        "id": "masks_apply_threshold",
        "title": "Make Binary",
        "category": "Masks",
        "description": "Create a binary labels layer by thresholding the selected image.",
        "tags": ["mask", "threshold", "apply", "selected-layer"],
        "best_for": "Creating a threshold-based labels layer directly from the active image.",
        "expected_input": "A selected grayscale image layer.",
        "parameter_hints": [
            "Default polarity is auto.",
            "Use bright or dim if the automatic foreground guess is wrong.",
        ],
        "prompt_examples": [
            "Make a binary labels layer from the selected image with polarity bright.",
            "Apply threshold to image_a with polarity dim.",
        ],
        "load_prompt": "Make a binary labels layer from the selected image.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "apply_threshold",
            "arguments": {"polarity": "auto"},
        },
    },
    {
        "id": "masks_preview_threshold_batch",
        "title": "Threshold Preview Batch",
        "category": "Masks",
        "description": "Preview thresholding across all open image layers.",
        "tags": ["mask", "threshold", "batch", "preview"],
        "best_for": "Checking rough threshold results across several images before applying them.",
        "expected_input": "Two or more open image layers.",
        "load_prompt": "Preview thresholding across all open image layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "preview_threshold_batch",
            "arguments": {"polarity": "auto"},
        },
    },
    {
        "id": "masks_apply_threshold_batch",
        "title": "Make Binary Batch",
        "category": "Masks",
        "description": "Create binary labels layers for all open image layers by thresholding.",
        "tags": ["mask", "threshold", "batch", "apply"],
        "best_for": "Applying the same threshold workflow across many images at once.",
        "expected_input": "Two or more open image layers.",
        "load_prompt": "Make binary labels layers from all open image layers.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "apply_threshold_batch",
            "arguments": {"polarity": "auto"},
        },
    },
    {
        "id": "masks_convert_to_mask",
        "title": "Convert To Mask",
        "category": "Masks",
        "description": "Convert the selected labels layer into a binary foreground mask.",
        "tags": ["mask", "binary", "selected-layer", "labels"],
        "best_for": "Flattening multi-label objects into one binary foreground mask.",
        "expected_input": "A selected Labels layer.",
        "parameter_hints": [
            "Uses the default behavior only: all nonzero labels become foreground 1.",
        ],
        "prompt_examples": [
            "Convert the selected labels layer to a binary mask.",
        ],
        "load_prompt": "Convert the selected labels layer to a binary mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "run_mask_op",
            "arguments": {"op": "convert_to_mask"},
        },
    },
    {
        "id": "masks_erode",
        "title": "Erode",
        "category": "Masks",
        "description": "Shrink the selected binary mask by one morphology step.",
        "tags": ["mask", "erode", "selected-layer"],
        "best_for": "Removing thin foreground fringes or separating nearly touching objects.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "Default radius is 1.",
            "Ask for radius 2 or 3 for stronger erosion.",
            "If you need repeated shrinking, ask for a larger radius.",
        ],
        "prompt_examples": [
            "Erode the selected mask with radius 2.",
            "Erode mask_a with radius 3.",
        ],
        "load_prompt": "Erode the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "erode", "radius": 1}},
    },
    {
        "id": "masks_dilate",
        "title": "Dilate",
        "category": "Masks",
        "description": "Expand the selected binary mask by one morphology step.",
        "tags": ["mask", "dilate", "selected-layer"],
        "best_for": "Bridging small gaps or growing a mask slightly before later cleanup.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "Default radius is 1.",
            "Ask for radius 2 or 3 to grow the mask more strongly.",
        ],
        "prompt_examples": [
            "Dilate the selected mask with radius 2.",
            "Dilate mask_a with radius 3.",
        ],
        "load_prompt": "Dilate the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "dilate", "radius": 1}},
    },
    {
        "id": "masks_open",
        "title": "Open",
        "category": "Masks",
        "description": "Run morphological opening on the selected binary mask.",
        "tags": ["mask", "open", "selected-layer"],
        "best_for": "Removing small protrusions or isolated foreground specks while preserving larger objects.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "Default radius is 1.",
            "Use a larger radius for stronger cleanup of thin noise.",
        ],
        "prompt_examples": [
            "Open the selected mask with radius 2.",
            "Open mask_a with radius 3.",
        ],
        "load_prompt": "Open the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "open", "radius": 1}},
    },
    {
        "id": "masks_close",
        "title": "Close",
        "category": "Masks",
        "description": "Run morphological closing on the selected binary mask.",
        "tags": ["mask", "close", "selected-layer"],
        "best_for": "Closing narrow breaks and smoothing small concavities in a binary mask.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "Default radius is 1.",
            "Use a larger radius to bridge wider gaps.",
        ],
        "prompt_examples": [
            "Close the selected mask with radius 2.",
            "Close mask_a with radius 3.",
        ],
        "load_prompt": "Close the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "close", "radius": 1}},
    },
    {
        "id": "masks_median",
        "title": "Median",
        "category": "Masks",
        "description": "Apply a median-style binary cleanup to the selected mask.",
        "tags": ["mask", "median", "selected-layer"],
        "best_for": "Reducing salt-and-pepper binary noise without a full open/close cycle.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "Default radius is 1.",
            "Use radius 2 or 3 for stronger binary smoothing.",
        ],
        "prompt_examples": [
            "Apply a median binary filter to the selected mask with radius 2.",
            "Median-filter mask_a with radius 3.",
        ],
        "load_prompt": "Apply a median binary filter to the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "median", "radius": 1}},
    },
    {
        "id": "masks_outline",
        "title": "Outline",
        "category": "Masks",
        "description": "Reduce the selected mask to its foreground outline.",
        "tags": ["mask", "outline", "selected-layer"],
        "best_for": "Converting filled binary objects into boundary traces.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "No extra parameter is used here.",
            "This produces a boundary mask from the current foreground.",
        ],
        "prompt_examples": [
            "Outline the selected mask.",
        ],
        "load_prompt": "Outline the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "outline"}},
    },
    {
        "id": "masks_fill_holes",
        "title": "Fill Mask Holes",
        "category": "Masks",
        "description": "Fill holes in the selected mask layer.",
        "tags": ["mask", "fill-holes", "selected-layer"],
        "best_for": "Quick cleanup of small holes in a selected mask.",
        "expected_input": "A selected Labels layer representing the mask to clean.",
        "parameter_hints": [
            "Current action uses the default fill behavior.",
            "If you want an area threshold, ask in Prompt for fill holes with a max hole size.",
        ],
        "prompt_examples": [
            "Fill holes in the selected mask.",
            "Fill holes in mask_a and keep only holes smaller than 100 pixels.",
        ],
        "load_prompt": "Fill holes in the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "fill_mask_holes",
            "arguments": {},
        },
    },
    {
        "id": "masks_skeletonize",
        "title": "Skeletonize",
        "category": "Masks",
        "description": "Reduce the selected mask to a one-pixel-wide skeleton.",
        "tags": ["mask", "skeleton", "selected-layer"],
        "best_for": "Centerline extraction from thin binary structures.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "No extra parameter is used here.",
        ],
        "prompt_examples": [
            "Skeletonize the selected mask.",
        ],
        "load_prompt": "Skeletonize the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "skeletonize"}},
    },
    {
        "id": "masks_distance_map",
        "title": "Distance Map",
        "category": "Masks",
        "description": "Create a distance-map image from the selected binary mask.",
        "tags": ["mask", "distance-map", "selected-layer"],
        "best_for": "Preparing seeds or measuring local thickness from a binary foreground mask.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "Current action uses the default Euclidean distance transform.",
        ],
        "prompt_examples": [
            "Create a distance map from the selected mask.",
        ],
        "load_prompt": "Create a distance map from the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "distance_map"}},
    },
    {
        "id": "masks_ultimate_points",
        "title": "Ultimate Points",
        "category": "Masks",
        "description": "Create marker labels from distance-transform maxima inside the selected mask.",
        "tags": ["mask", "ultimate-points", "selected-layer"],
        "best_for": "Generating marker seeds before watershed-style separation.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "Current action uses local maxima of the distance map.",
        ],
        "prompt_examples": [
            "Find ultimate points in the selected mask.",
        ],
        "load_prompt": "Find ultimate points in the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "ultimate_points"}},
    },
    {
        "id": "masks_watershed",
        "title": "Watershed",
        "category": "Masks",
        "description": "Split touching mask regions with a distance-transform watershed.",
        "tags": ["mask", "watershed", "selected-layer"],
        "best_for": "Separating merged binary objects into instance-like labels.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "Current action uses distance-map maxima as markers.",
            "If you need control over markers or smoothing, ask in Prompt.",
        ],
        "prompt_examples": [
            "Run watershed on the selected mask.",
            "Run watershed on mask_a after smoothing it with sigma 1.5.",
        ],
        "load_prompt": "Run watershed on the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "watershed"}},
    },
    {
        "id": "masks_voronoi",
        "title": "Voronoi",
        "category": "Masks",
        "description": "Create Voronoi-like nearest-object regions from the selected binary mask.",
        "tags": ["mask", "voronoi", "selected-layer"],
        "best_for": "Partitioning space by proximity to binary objects.",
        "expected_input": "A selected Labels mask layer.",
        "parameter_hints": [
            "Current action uses connected components as Voronoi seeds.",
        ],
        "prompt_examples": [
            "Create Voronoi regions from the selected mask.",
        ],
        "load_prompt": "Create Voronoi regions from the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {"kind": "tool", "target": "run_mask_op", "arguments": {"op": "voronoi"}},
    },
    {
        "id": "masks_remove_small_objects",
        "title": "Remove Small Particles",
        "category": "Masks",
        "description": "Remove small connected components from the selected mask layer.",
        "tags": ["mask", "cleanup", "selected-layer", "labels"],
        "best_for": "Removing speckle-like components from a selected mask.",
        "expected_input": "A selected Labels layer representing the mask to clean.",
        "parameter_hints": [
            "Default min_size is 64.",
            "Increase min_size to remove more small particles.",
        ],
        "prompt_examples": [
            "Remove small objects from the selected mask with min_size 128.",
            "Remove small objects from mask_a with min_size 32.",
        ],
        "load_prompt": "Remove small objects from the selected mask with min_size 64.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "remove_small_objects",
            "arguments": {"min_size": 64},
        },
    },
    {
        "id": "masks_keep_largest_component",
        "title": "Keep Largest Object",
        "category": "Masks",
        "description": "Keep only the largest connected component in the selected mask layer.",
        "tags": ["mask", "cleanup", "largest", "selected-layer"],
        "best_for": "Reducing a rough mask to its dominant connected object quickly.",
        "expected_input": "A selected Labels layer representing the mask to clean.",
        "parameter_hints": [
            "No extra parameter is used here.",
        ],
        "prompt_examples": [
            "Keep only the largest connected component in the selected mask.",
        ],
        "load_prompt": "Keep only the largest connected component in the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "keep_largest_component",
            "arguments": {},
        },
    },
    {
        "id": "masks_label_connected_components",
        "title": "Connected Components",
        "category": "Masks",
        "description": "Convert the selected binary mask into connected-component instance labels.",
        "tags": ["mask", "labels", "instances", "selected-layer"],
        "best_for": "Turning a binary foreground mask into separate object labels.",
        "expected_input": "A selected binary mask or labels-like layer.",
        "parameter_hints": [
            "Default connectivity is 1.",
            "Ask for connectivity 2 in 2D or higher connectivity in 3D when you want diagonally touching pixels to connect.",
        ],
        "prompt_examples": [
            "Label connected components in the selected mask with connectivity 1.",
            "Label connected components in mask_a with connectivity 2.",
        ],
        "load_prompt": "Label connected components in the selected mask.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "label_connected_components",
            "arguments": {},
        },
    },
    {
        "id": "montage_create_analysis",
        "title": "Make Analysis Montage",
        "category": "Montage",
        "description": "Build one composite montage canvas with a blank mask layer for shared ROI or mask editing.",
        "tags": ["montage", "analysis", "canvas", "labels"],
        "best_for": "Mask or ROI work across several 2D grayscale image layers in one coordinate space.",
        "expected_input": "Two or more 2D grayscale image layers.",
        "load_prompt": "Make an analysis montage from the open image layers with spacing 2 and tile boxes.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "create_analysis_montage",
            "arguments": {"rows": 1, "columns": 3, "spacing": 2, "show_tile_boxes": True, "create_mask_layer": True},
        },
    },
    {
        "id": "montage_split_annotations",
        "title": "Split Montage Back To Sources",
        "category": "Montage",
        "description": "Split montage-space labels or points back into per-source layers.",
        "tags": ["montage", "split", "labels", "points"],
        "best_for": "Returning montage annotations to one layer per source image after shared editing.",
        "expected_input": "An analysis montage plus a montage labels or points layer created from that montage.",
        "load_prompt": "Split the montage annotations back to the source images.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "split_montage_annotations_to_sources",
            "arguments": {},
        },
    },
    {
        "id": "segmentation_sam2_setup",
        "title": "Segment Anything 2 Setup",
        "category": "Segmentation",
        "group": "SAM2 Session",
        "description": "Open the SAM2 setup dialog for project path, checkpoint, config, and device.",
        "tags": ["segmentation", "sam2", "setup", "widget"],
        "best_for": "Configuring the local SAM2 backend before using the SAM2 actions.",
        "expected_input": "No layer input required.",
        "load_prompt": "Open SAM2 setup.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "function",
            "target": "show_sam2_setup_dialog",
        },
    },
    {
        "id": "segmentation_sam2_live",
        "title": "Segment Anything 2 Live",
        "category": "Segmentation",
        "group": "SAM2 Session",
        "description": "Open the interactive SAM2 Live preview dialog.",
        "tags": ["segmentation", "sam2", "live", "widget"],
        "best_for": "Interactive preview when you want to guide SAM2 with boxes or managed points.",
        "expected_input": "A grayscale image layer and a working SAM2 backend.",
        "load_prompt": "Open SAM2 Live.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "function",
            "target": "show_sam2_live_dialog",
        },
    },
    {
        "id": "segmentation_sam2_auto_segment",
        "title": "SAM Auto Segment",
        "category": "Segmentation",
        "description": "Run automatic SAM2 segmentation on the selected image layer.",
        "tags": ["segmentation", "sam2", "sam", "auto", "selected-layer"],
        "best_for": "Quick first-pass segmentation when the target object dominates the image and you want a no-prompt SAM2 attempt.",
        "expected_input": "A selected image layer and a working SAM/SAM2 backend.",
        "how_it_works": "This action currently prompts SAM2 with the whole image as one coarse region. It is fast, but it can choose the dominant structure or even background if the target is ambiguous.",
        "workflow": [
            "Select a 2D grayscale image layer.",
            "Run this action.",
            "Inspect the new labels layer and keep it only if the object choice is reasonable.",
            "If it chooses the wrong structure, switch to Box or Points prompting.",
        ],
        "load_prompt": "Run SAM2 auto segmentation on the selected image.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "sam_auto_segment",
            "arguments": {},
        },
    },
    {
        "id": "segmentation_sam2_segment_from_box",
        "title": "Segment From ROI Box",
        "category": "Segmentation",
        "description": "Run SAM2 segmentation from a selected box or Shapes ROI layer.",
        "tags": ["segmentation", "sam2", "sam", "box", "roi"],
        "best_for": "Prompted segmentation when you want SAM2 to focus on one object in a smaller spatial region.",
        "expected_input": "An image layer, a box/rectangle Shapes ROI, and a working SAM/SAM2 backend.",
        "how_it_works": "The box acts as the prompt. SAM2 treats the boxed region as the place where the intended object lives, so tighter boxes usually work better than large loose boxes.",
        "workflow": [
            "Select or draw a rectangle or box-like Shapes ROI around the target object.",
            "Run this action.",
            "Check the new labels result.",
            "If the object is still ambiguous, use a tighter box or move to the point workflow.",
        ],
        "load_prompt": "Run SAM2 segmentation from the current box ROI.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "sam_segment_from_box",
            "arguments": {},
        },
    },
    {
        "id": "segmentation_sam2_refine_mask",
        "title": "Refine From Mask",
        "category": "Segmentation",
        "description": "Refine an existing mask layer using the SAM2 backend.",
        "tags": ["segmentation", "sam2", "sam", "mask", "refine"],
        "best_for": "Re-prompting a rough mask when you want SAM2 to rebuild the object from the current mask hint.",
        "expected_input": "An image layer, an existing mask layer, and a working SAM/SAM2 backend.",
        "how_it_works": "The current implementation converts the mask into a bounding box plus positive interior points, then asks SAM2 to predict again. This is useful for re-segmentation, not for pure boundary smoothing.",
        "workflow": [
            "Select an image and the rough labels mask you want to improve.",
            "Run this action.",
            "Compare the refined result with the input mask.",
            "If your goal is edge smoothing rather than re-segmentation, use morphology tools instead.",
        ],
        "load_prompt": "Refine the current mask with SAM2.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "sam_refine_mask",
            "arguments": {},
        },
    },
    {
        "id": "segmentation_sam2_points_init",
        "title": "Initialize SAM2 Points",
        "category": "Segmentation",
        "group": "SAM2 Points",
        "description": "Create or reuse a SAM2-managed points layer for the selected image.",
        "tags": ["segmentation", "sam2", "points", "prompts", "selected-layer"],
        "best_for": "Starting point-guided SAM2 segmentation without opening the full SAM2 Live dialog.",
        "expected_input": "A selected 2D or 3D grayscale image layer and a working SAM/SAM2 backend.",
        "how_it_works": "This creates a managed points layer named after the image. New points start as positive prompts. Press T on the active SAM2 points layer to toggle the polarity for new points, or to flip selected points.",
        "workflow": [
            "Select a grayscale image layer.",
            "Run Initialize SAM2 Points.",
            "Add positive and negative prompt points on the created SAM2 points layer.",
            "Run Segment From Points for 2D or Propagate Through Z for 3D volumes.",
        ],
        "load_prompt": "Initialize a SAM2 points layer for the selected image.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "function",
            "target": "initialize_sam2_points_layer",
        },
    },
    {
        "id": "segmentation_sam2_segment_from_points",
        "title": "Segment From Points",
        "category": "Segmentation",
        "group": "SAM2 Points",
        "description": "Run 2D SAM2 segmentation from the managed points prompts.",
        "tags": ["segmentation", "sam2", "points", "2d"],
        "best_for": "Prompted 2D segmentation when a box is not specific enough and you want positive and negative guidance.",
        "expected_input": "A selected 2D grayscale image and a SAM2-managed points layer created with Initialize SAM2 Points.",
        "how_it_works": "SAM2 reads the per-point prompt labels from the managed points layer. Positive points tell it what to include. Negative points tell it what to avoid.",
        "workflow": [
            "Run Initialize SAM2 Points first.",
            "Place positive and negative prompt points on the SAM2 points layer.",
            "Run this action to generate a labels mask.",
            "If needed, add or move points and run it again.",
        ],
        "load_prompt": "Run SAM2 segmentation from the current points prompts.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "sam_segment_from_points",
            "arguments": {},
        },
    },
    {
        "id": "segmentation_sam2_propagate_points_3d",
        "title": "Propagate Through Z",
        "category": "Segmentation",
        "group": "SAM2 Points",
        "description": "Run 3D SAM2 propagation from point prompts on a single seed slice.",
        "tags": ["segmentation", "sam2", "points", "3d", "propagate"],
        "best_for": "Volume segmentation when you want to seed one slice with point prompts and propagate the result through z.",
        "expected_input": "A selected 3D grayscale image and a SAM2-managed points layer with prompts on one z slice.",
        "how_it_works": "SAM2 reads the prompt points from one seed slice, predicts there, and propagates the object through the volume. All selected prompts must lie on the same z slice.",
        "workflow": [
            "Run Initialize SAM2 Points on a 3D image.",
            "Move to the desired seed slice and place positive and negative prompt points on that slice.",
            "Run this action to propagate the segmentation through the stack.",
            "If propagation is off, adjust the seed prompts and run again.",
        ],
        "load_prompt": "Propagate the SAM2 point prompts through the current 3D image.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "sam_propagate_points_3d",
            "arguments": {},
        },
    },
    {
        "id": "segmentation_extract_axon_interiors",
        "title": "Detect Axon Interiors",
        "category": "Segmentation",
        "description": "Extract candidate axon interiors from a 2D grayscale EM image.",
        "tags": ["segmentation", "axon", "em", "interiors"],
        "best_for": "Finding dark-ring-enclosed interior regions in EM-like grayscale images.",
        "expected_input": "A 2D grayscale EM image layer.",
        "load_prompt": "Extract candidate axon interiors from the selected image.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": True,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "extract_axon_interiors",
            "arguments": {},
        },
    },
    {
        "id": "spectral_open_nd2_converter",
        "title": "ND2 to OME-Zarr",
        "category": "Spectral",
        "description": "Open the ND2 to OME-Zarr conversion workflow.",
        "tags": ["spectral", "nd2", "converter", "ome-zarr"],
        "best_for": "Launching the dedicated converter without asking chat.",
        "expected_input": "No layer input required.",
        "load_prompt": "Open the ND2 converter.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "open_nd2_converter",
            "arguments": {},
        },
    },
    {
        "id": "spectral_open_viewer",
        "title": "Spectral Viewer",
        "category": "Spectral",
        "description": "Open the spectral viewer workflow widget.",
        "tags": ["spectral", "viewer", "widget"],
        "best_for": "Launching the dedicated spectral viewer directly from the Actions catalog.",
        "expected_input": "A spectral workflow context in the current viewer.",
        "load_prompt": "Open the spectral viewer.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "open_spectral_viewer",
            "arguments": {},
        },
    },
    {
        "id": "spectral_open_analysis",
        "title": "Spectral Analysis",
        "category": "Spectral",
        "description": "Open the spectral analysis workflow widget.",
        "tags": ["spectral", "analysis", "widget"],
        "best_for": "Launching the dedicated spectral analysis workflow directly.",
        "expected_input": "A spectral workflow context in the current viewer.",
        "load_prompt": "Open the spectral analysis workflow.",
        "runtime": {
            "plugin_runtime_required": True,
            "uses_viewer": True,
            "uses_selected_layer": False,
            "uses_run_in_background": False,
        },
        "execution": {
            "kind": "tool",
            "target": "open_spectral_analysis",
            "arguments": {},
        },
    },
]


def action_library_payload() -> dict[str, Any]:
    return {
        "version": ACTION_LIBRARY_VERSION,
        "categories": list(ACTION_CATEGORIES),
        "actions": [dict(record) for record in ACTION_RECORDS],
    }
